# Generated by Django 6.0.5 on 2026-06-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_business_price_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='gateway_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('stripe', 'Stripe'), ('click', 'Click'), ('payme', 'Payme')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutish'), ('confirmed', 'Tasdiqlangan'), ('paid', 'Toʻlangan'), ('failed', 'Rad etilgan')], default='pending', max_length=20),
        ),
    ]
