# Generated by Django 6.0.5 on 2026-06-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_booking_external_id_booking_gateway_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('reservation', 'Joyda rezerv'), ('delivery', 'Dostafka')], default='reservation', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
