# Generated by Django 6.0.5 on 2026-06-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_booking_booking_type_booking_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reservation_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
