# Generated by Django 6.0.5 on 2026-06-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_booking_reservation_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reservation_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
