# Generated by Django 6.0.5 on 2026-06-06 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_booking_room_type_business_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Single (SGL)', 'Single (SGL)'), ('Double (DBL)', 'Double (DBL)'), ('Twin (TWN)', 'Twin (TWN)'), ('Triple (TRPL)', 'Triple (TRPL)'), ('Quadruple (QDPL)', 'Quadruple (QDPL)'), ('Family Room', 'Family Room'), ('Standard', 'Standard'), ('Superior', 'Superior'), ('Deluxe', 'Deluxe'), ('Suite / Luxe', 'Suite / Luxe'), ('Junior Suite', 'Junior Suite'), ('Apartment / Studio', 'Apartment / Studio')], max_length=50)),
                ('image', models.ImageField(upload_to='business/rooms/')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='main.business')),
            ],
            options={
                'verbose_name': 'Hotel Room Image',
                'verbose_name_plural': 'Hotel Room Images',
            },
        ),
    ]
