# Generated by Django 6.0.5 on 2026-06-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_hotelroomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
