# Generated by Django 6.0.5 on 2026-06-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_business_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='business',
            name='owner_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='owner_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='owner_passport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
