# Generated by Django 6.0 on 2026-06-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_booking_jshshr_booking_passport_series_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroomimage',
            name='room_type',
            field=models.CharField(choices=[('1 kishilik', '1 kishilik'), ('2 kishilik', '2 kishilik'), ('Twin (TWN)', 'Twin (TWN)'), ('Triple (TRPL)', 'Triple (TRPL)'), ('Quadruple (QDPL)', 'Quadruple (QDPL)'), ('Family Room', 'Oila xonasi'), ('Standard', 'Standard'), ('Superior', 'Superior'), ('Deluxe', 'Deluxe'), ('Suite / Luxe', 'Suite / Luxe'), ('Junior Suite', 'Junior Suite'), ('Apartment / Studio', 'Apartment / Studio')], max_length=50),
        ),
    ]
