# Generated by Django 6.0 on 2026-06-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_hotelroomimage_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroomimage',
            name='room_type',
            field=models.CharField(choices=[('Single (SGL)', 'Yagona xona (SGL)'), ('Double (DBL)', 'Qosh xona (DBL)'), ('Twin (TWN)', 'Ikki tosak (TWN)'), ('Triple (TRPL)', 'Uchlik (TRPL)'), ('Quadruple (QDPL)', 'Torlik (QDPL)'), ('Family Room', 'Oila xonasi'), ('Standard', 'Standart'), ('Superior', 'Superior'), ('Deluxe', 'Deluxe'), ('Suite / Luxe', 'Suit/Lyuks'), ('Junior Suite', 'Kichik Suit'), ('Apartment / Studio', 'Apartament/Studio')], max_length=50),
        ),
    ]
